jobs:
  - job: Plan
    displayName: Terraform Plan
    workspace:
      clean: all
    steps:
      - task: Cmdline@2
        displayName: >-
          multiline
          displayname
        inputs:
          script: >-
            echo "
            terraform
            $(key)
            plan
            -out=terraform.tfplan
            -var
            -var
            -var
            -var
            -var"
